name: Examples

on:
  push:
    branches: [ main ]

jobs:
  deploy_to_ghpages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install deps and build Vite example
        run: |
          cd examples/vite-react-app
          yarn
          yarn build
        env:
         CI: ""
         BASE_URL: "/vocdoni-sdk"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: examples/vite-react-app/dist
