name: Deploy examples to GH pages

on:
  push:
    branches: [ main ]

jobs:
  deploy_to_ghpages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install deps and build SDK
        run: |
          yarn
          yarn build

      - name: Install deps and build CRA example
        run: |
          cd examples/cra
          yarn
          yarn build
        env:
         CI: ""
         PUBLIC_URL: "/vocdoni-sdk"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: examples/cra/build
